-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    user_id integer NOT NULL,
    user_name text NOT NULL,
    password text NOT NULL,
    email text NOT NULL,
    user_type text NOT NULL,
    name text NOT NULL,
    surname text NOT NULL,
    create_date date NOT NULL,
    phone_number integer,
    PRIMARY KEY (user_id)
    );

CREATE TABLE IF NOT EXISTS public."Order"
(
    order_id integer NOT NULL,
    user_id_seller integer NOT NULL,
    user_id_buyer integer NOT NULL,
    date_of_order date NOT NULL,
    price_of_order money NOT NULL,
    payment_type text NOT NULL,
    PRIMARY KEY (order_id)
    );

CREATE TABLE IF NOT EXISTS public."OrderDetails"
(
    order_id integer NOT NULL,
    offer_id integer NOT NULL,
    number_of_units real NOT NULL,
    price_of_offer money NOT NULL,
    PRIMARY KEY (order_id, offer_id)
    );

CREATE TABLE IF NOT EXISTS public."Offer"
(
    offer_id integer,
    user_id integer,
    product_name text,
    unit_of_measure text,
    unit real,
    start_of_offer date,
    end_of_offer date,
    price_per_unit_of_measure money,
    location_city text,
    location_street text,
    PRIMARY KEY (offer_id)
    );

ALTER TABLE IF EXISTS public."Order"
    ADD FOREIGN KEY (user_id_seller)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order"
    ADD FOREIGN KEY (user_id_buyer)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderDetails"
    ADD FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderDetails"
    ADD FOREIGN KEY (offer_id)
    REFERENCES public."Offer" (offer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Offer"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;